version: "3.7"
services:
  nginx:
    image: nginx:alpine
    # 80(http), 443(https) for frontend; 2333 for backend api;
    ports:
      - "80:80"
      - "443:443"
      - "2333:2333"
    volumes:
      - ./src/:/var/www/:rw
      - ./config/nginx/server:/etc/nginx/server/:ro
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /var/lib/letsencrypt/:/var/lib/letsencrypt/
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./env/logs/nginx/:/var/log/nginx/:rw
    depends_on:
      - php
    networks:
      - parse

  php:
    build: ./env/images/php/
    expose:
      - "9000"
    volumes:
      - ./src/:/var/www/:rw
      - ./config/php/php.ini:/usr/local/etc/php/php.ini:rw
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
      - ./env/logs/php-fpm/:/usr/local/var/log/php-fpm/:rw
    networks:
      - parse
      - data
    environment:
      - REDIS_PORT=6379
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_NO_INTERACTION=1

  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - data
    volumes:
      - ./env/data/pgsql/db.sql:/var/lib/postgresql/db.sql:rw
    # - ./config/pgsql/postgresql.conf:/var/lib/postgresql/data/postgresql.conf
    # - ./config/pgsql/pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - data
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

networks:
  parse:
  data:
